### ISSUE TITLE
Extra characters added to all slides when building a pro6 file

### ISSUE THREAD

**Issue by eapariciodev** [ChrisMBarr/ProPresenter-Parser#72]
https://github.com/ChrisMBarr/ProPresenter-Parser/blob/236f6d87944a6e4ec236bd15b1ab0313cfa25d1f/src/utils.ts#L19

I don't know anything about the RTF format, but are the `',` characters after `\\cocoasubrtf320` correct? I ask because when I import a pro6 document generated from this library all of my slides end up with those characters at the beginning of the text.

I'm on an M1 Mac, if that matters. I saw another issue where apparently Propresenter 7 uses the RTFData field. That led me to looking into how the RTF is generated and seeing those exact characters in the `formatRtf` utility method just seemed suspicious.

**Comment by ChrisMBarr** [comment]
I hate RTF so much, haha. I'll have to look into this. Can you provide some input file/data and what it generated as output?

**Comment by eapariciodev** [comment]
This basic sample produces the attached file. The decoded `PlainText` string is fine. The decoded `RTFData` seemingly has the extra characters.

```
const pro6Xml = ProPresenter6Builder({
  slideGroups: [{ slides: ['Test 1', 'Test 2', 'Test 3'] }],
});
```

I had to add the `.txt` extension so Github would let me attach the file, but it's just the generated ProPresenter 6 doc.
[test.pro6.txt](https://github.com/user-attachments/files/16808495/test.pro6.txt)

**Comment by ChrisMBarr** [comment]
Ok, finally got around to looking at this, and I think it might truly be as simple as just removing those extra character - RTF is weird to me and difficult to understand, so a lot of what I have in there was just me copy/pasting "working" RTF data and inserting the text between the formatting characters.

Something I learned recently is that ProPresenter on a Mac seems to read a different property that a Windows machine does. Those `Win*` properties are used by Windows, and the `RTFData` property seems to be used by a Mac.

```xml
<NSString rvXMLIvarName="PlainText">...</NSString>
<NSString rvXMLIvarName="RTFData">...</NSString>
<NSString rvXMLIvarName="WinFlowData">...</NSString>
<NSString rvXMLIvarName="WinFontData">...</NSString>
```

So I am on a Windows machine here, and from my prespective it all seemed to work but I had no idea different platforms would read things differently!  So, before I commit a fix to this I will need some confirmation that this is working as I expect it to.  I am using this from one of my unit tests to generate a `*.pro6` file:


```ts
const builder = new v6Builder({
  properties: {
    CCLISongTitle: 'My Test Song',
  },
  slideGroups: [
    {
      label: 'Verse 1',
      slides: ['Hello World\nline 2'],
    },
  ],
});
```

And below are the outputs of that before and after the fix of just removing those characters from the RTF string.

### [📄 before.txt](https://github.com/user-attachments/files/16922547/before.txt) | [📄 after.txt](https://github.com/user-attachments/files/16922548/after.txt)

Please download these, change the file extension to `pro6`, import them into ProPresenter, and let me know if this fixes this issue for you or not

**Comment by eapariciodev** [comment]
Yep, the "after" file looks good.

The "before" one had an extra ` at the very end of the xml and wouldn't import. Once I removed that then it imported and had the extra characters in the slide text.

**Comment by ChrisMBarr** [comment]
Cool! I'm gonna update my unit tests and publish a new release with that fix soon then. Thanks for the confirmation!
